// <auto-generated />
using System;
using System.Collections.Generic;
using Axiom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Axiom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AxiomDbContext))]
    [Migration("20261003225817_AddGovernanceProjection")]
    partial class AddGovernanceProjection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("axiom")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceRecordRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("record_id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("author");

                    b.Property<string>("BlobSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_sha");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.PrimitiveCollection<List<string>>("Owners")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("owners");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<DateOnly?>("ReviewAfter")
                        .HasColumnType("date")
                        .HasColumnName("review_after");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "RecordId", "Title", "Statement", "TagsText" });

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("TagsText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("OrganizationId", "RecordId")
                        .HasName("pk_governance_record");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_governance_record_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("OrganizationId", "Kind")
                        .HasDatabaseName("ix_governance_record_kind");

                    b.HasIndex("OrganizationId", "Status", "ReviewAfter")
                        .HasDatabaseName("ix_governance_record_status_review");

                    b.ToTable("governance_record", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceRelationRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("record_id");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("TargetId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("target_id");

                    b.HasKey("OrganizationId", "RecordId", "Kind", "TargetId")
                        .HasName("pk_governance_relation");

                    b.HasIndex("OrganizationId", "TargetId")
                        .HasDatabaseName("ix_governance_relation_target");

                    b.ToTable("governance_relation", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceRevisionRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("record_id");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("author");

                    b.Property<string>("BlobSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_sha");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("OrganizationId", "RecordId", "Revision")
                        .HasName("pk_governance_revision");

                    b.HasIndex("OrganizationId", "RecordId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ux_governance_revision_content");

                    b.ToTable("governance_revision", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceScopeRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("record_id");

                    b.Property<string>("Dimension")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dimension");

                    b.Property<string>("ValueKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value_key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("OrganizationId", "RecordId", "Dimension", "ValueKey")
                        .HasName("pk_governance_scope");

                    b.HasIndex("OrganizationId", "Dimension", "ValueKey")
                        .HasDatabaseName("ix_governance_scope_value");

                    b.ToTable("governance_scope", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceSnapshotEntryRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("record_id");

                    b.Property<int>("FromSequence")
                        .HasColumnType("integer")
                        .HasColumnName("from_sequence");

                    b.Property<string>("BlobSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_sha");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("Path")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("path");

                    b.Property<int?>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.HasKey("OrganizationId", "RecordId", "FromSequence")
                        .HasName("pk_governance_snapshot_entry");

                    b.ToTable("governance_snapshot_entry", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceSnapshotRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("SourceCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_commit");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("author");

                    b.Property<DateTimeOffset>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("OrganizationId", "SourceCommit")
                        .HasName("pk_governance_snapshot");

                    b.HasIndex("OrganizationId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_governance_snapshot_sequence");

                    b.HasIndex("OrganizationId", "SnapshotId")
                        .HasDatabaseName("ix_governance_snapshot_id");

                    b.ToTable("governance_snapshot", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.GovernanceSourceRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("root_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OrganizationId")
                        .HasName("pk_governance_source");

                    b.ToTable("governance_source", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Governance.Persistence.SyncCheckpointRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch");

                    b.Property<string>("HeadCommit")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("head_commit");

                    b.Property<string>("HeadOutcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("head_outcome");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("issues");

                    b.Property<string>("PublishedCommit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("published_commit");

                    b.Property<int>("PublishedSequence")
                        .HasColumnType("integer")
                        .HasColumnName("published_sequence");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("record_count");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("root_path");

                    b.Property<string>("SnapshotId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("snapshot_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("OrganizationId")
                        .HasName("pk_sync_checkpoint");

                    b.ToTable("sync_checkpoint", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Persistence.OutboxEvent", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.HasKey("OrganizationId", "EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_event_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_event", "axiom");
                });
#pragma warning restore 612, 618
        }
    }
}
