// <auto-generated />
using System;
using Axiom.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Axiom.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AxiomDbContext))]
    [Migration("20261003230117_AddCatalog")]
    partial class AddCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("axiom")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.CatalogStateRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationId");

                    b.ToTable("catalog_state", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.RepositoryBindingRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("Alias")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("alias");

                    b.Property<string>("AliasType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("alias_type");

                    b.Property<string>("RepositoryRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("repository_ref");

                    b.HasKey("OrganizationId", "Alias", "AliasType", "RepositoryRef");

                    b.HasIndex("OrganizationId", "RepositoryRef")
                        .HasDatabaseName("ix_repository_binding_repository");

                    b.ToTable("repository_binding", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.SoftwareEdgeObservationRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("source_ref");

                    b.Property<string>("Relation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation");

                    b.Property<string>("TargetRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("target_ref");

                    b.Property<string>("SourceLocator")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_locator");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.HasKey("OrganizationId", "SourceRef", "Relation", "TargetRef", "SourceLocator");

                    b.HasIndex("OrganizationId", "SourceLocator")
                        .HasDatabaseName("ix_software_edge_observation_locator");

                    b.ToTable("software_edge_observation", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.SoftwareEdgeRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("SourceRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("source_ref");

                    b.Property<string>("Relation")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("relation");

                    b.Property<string>("TargetRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("target_ref");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<string>("ConfirmedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<bool>("IsFact")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fact");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_locator");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.HasKey("OrganizationId", "SourceRef", "Relation", "TargetRef");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_software_edge_unconfirmed")
                        .HasFilter("NOT is_fact");

                    b.HasIndex("OrganizationId", "Relation")
                        .HasDatabaseName("ix_software_edge_relation");

                    b.HasIndex("OrganizationId", "TargetRef", "Relation", "SourceRef")
                        .HasDatabaseName("ix_software_edge_reverse");

                    b.ToTable("software_edge", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.SoftwareEntityObservationRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("EntityRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("entity_ref");

                    b.Property<string>("SourceLocator")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_locator");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.PrimitiveCollection<string[]>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("technologies");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("OrganizationId", "EntityRef", "SourceLocator");

                    b.HasIndex("OrganizationId", "SourceLocator")
                        .HasDatabaseName("ix_software_entity_observation_locator");

                    b.ToTable("software_entity_observation", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Catalog.Persistence.SoftwareEntityRow", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("EntityRef")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("entity_ref");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision")
                        .HasColumnName("confidence");

                    b.Property<bool>("Confirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("confirmed");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen");

                    b.Property<bool>("IsFact")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fact");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("name");

                    b.Property<string>("SourceLocator")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_locator");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source_type");

                    b.PrimitiveCollection<string[]>("Technologies")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("technologies");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("title");

                    b.HasKey("OrganizationId", "EntityRef");

                    b.HasIndex("OrganizationId", "LastSeen")
                        .HasDatabaseName("ix_software_entity_last_seen");

                    b.HasIndex("OrganizationId", "Kind", "EntityRef")
                        .HasDatabaseName("ix_software_entity_kind");

                    b.ToTable("software_entity", "axiom");
                });

            modelBuilder.Entity("Axiom.Infrastructure.Persistence.OutboxEvent", b =>
                {
                    b.Property<string>("OrganizationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("organization_id");

                    b.Property<string>("EventId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("schema_version");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.HasKey("OrganizationId", "EventId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_event_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_event", "axiom");
                });
#pragma warning restore 612, 618
        }
    }
}
