apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "axiom.fullname" . }}
  labels: {{- include "axiom.labels" . | nindent 4 }}
data:
  {{- if not .Values.auth.devMode.enabled }}
  Axiom__Auth__Authority: {{ required "auth.authority is required unless auth.devMode.enabled" .Values.auth.authority | quote }}
  {{- end }}
  Axiom__Auth__Audience: {{ .Values.auth.audience | quote }}
  Axiom__Auth__PortalClientId: {{ .Values.auth.portalClientId | quote }}
  Axiom__Auth__OrganizationClaim: {{ .Values.auth.organizationClaim | quote }}
  Axiom__Auth__RolesClaim: {{ .Values.auth.rolesClaim | quote }}
  Axiom__Auth__TeamsClaim: {{ .Values.auth.teamsClaim | quote }}
  {{- with .Values.publicBaseUrl }}
  Axiom__PublicBaseUrl: {{ . | quote }}
  {{- end }}
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
